### PR TITLE
mixingmatrix() documented separately and other fixes

### LINKED ISSUE #6: mixingmatrix function -- no man page entry
is there a reason?

### PR DESCRIPTION
**Pull request by mbojan**
Summary of the changes:

- `mixingmatrix()` and methods has now a separate man page (fixes #6 )
- `is.color()`, `has.edges()`, `as.color()`, `network.density()`, `which.matrix.type()` in separate man pages
- Only `networkOperatorSetup()` and functions in `R/misc.R` remain documented under "network-internal" topic.
- Minor documentation cleanups

### CODE REVIEW

**Comment by krivit** [comment]
Thanks for the PR! For the sake of change tracking, I would rather not split up functions into separate files unless there is a very compelling reason to do so. Can you put them back together and in the same order, please?

P.S. It occurs to me that `as.color()` should be a generic, but that can wait.

**Comment by mbojan** [comment]
> Thanks for the PR! For the sake of change tracking, I would rather not split up functions into separate files unless there is a very compelling reason to do so. Can you put them back together and in the same order, please?

Ugh, ok no problem. I'll add commits here.


> P.S. It occurs to me that `as.color()` should be a generic, but that can wait.

OK, made #37.

**Comment by mbojan** [comment]
@krivit , I have put everything back to `R/misc.R` as you requested. Added a rudimentary `mixingmatrix()` example on the way. I think this is ready to merge.

**Comment by krivit** [comment]
@mbojan , thanks! I've made some tweaks to minimise discrepancy with master. If you don't mind, I'm going to squash some of the commits so as to not break revision tracking.

**Comment by mbojan** [comment]
Sure @krivit

**Pull request merged**
