### PR TITLE
convert documentation to roxygen

### PR DESCRIPTION
**Pull request by chad-klumb**
closes statnet/network#11

### CODE REVIEW

**Comment by chad-klumb** [comment]
build errors appear to be related to .Rd links to package `ergm`

not sure why this is showing up now, since those were in the existing versions of the .Rd files as well

**Comment by chad-klumb** [comment]
looks like the same issue was present in build #57 but as a note rather than a warning

**Comment by chad-klumb** [comment]
removed two links to package `ergm` (other option was making `network` suggest `ergm`)

build failures now appear related to CRAN connectivity issues

**Comment by skyebend** [comment]
this looks amazing! (and a huge amount of work!).  how will we test the reverse dependencies to make sure they are not broken by subtle changes to namespace?

**Comment by chad-klumb** [comment]
I believe the two NAMESPACEs are equivalent; we are currently running revdeps on statnet2

closed/re-opened the PR to get travis to run again, but it now appears to be failing due to a different connectivity issue:

```
 ERROR
Running the tests in â€˜tests/read.paj_tests.Râ€™ failed.
Last 13 lines of output:
  > 
  > #issue with read.table and number.cols and fill...SanJuanSur_deathmessage.net has one row with 8 all the rest (including the first 5 have 5)
  > 
  > 
  > 
  > # this file has character encoding issues
  > scotland<-tempfile('scotland',fileext='.zip')
  > download.file('http://vlado.fmf.uni-lj.si/pub/networks/data/esna/scotland.zip',scotland)
  trying URL 'http://vlado.fmf.uni-lj.si/pub/networks/data/esna/scotland.zip'
  Error in download.file("http://vlado.fmf.uni-lj.si/pub/networks/data/esna/scotland.zip",  : 
    cannot open URL 'http://vlado.fmf.uni-lj.si/pub/networks/data/esna/scotland.zip'
  In addition: Warning message:
  In download.file("http://vlado.fmf.uni-lj.si/pub/networks/data/esna/scotland.zip",  :
    URL 'http://vlado.fmf.uni-lj.si/pub/networks/data/esna/scotland.zip': status was 'Couldn't connect to server'
  Execution halted
```

**Comment by chad-klumb** [comment]
I hope to return to this after #14 (which is of more immediate importance) is merged.  I can compare revdeps for this against `master` as I did for #14, so that even if we can't test every last one, we can see that there are no new errors among those that we can test.

**Comment by krivit** [comment]
Great work, Chad!

Regarding the download test, we could condition it on environment variable `_R_CHECK_CRAN_INCOMING_REMOTE_` not being set to "off" (or similar).

@CarterButts , since you are the maintainer, do you want to give this a once-over before merging?

**Comment by skyebend** [comment]
I looked at diffs for a bunch of the .rd files, and they look much better than the original.

**Comment by krivit** [comment]
Looks like merging PR #14 broke this PR. Meanwhile, there haven't been any objections from Carter. @chad-klumb , can you reconcile these changes, and then we'll merge?

**Comment by chad-klumb** [comment]
believe merge conflicts have been resolved

will try running revdeps tonight; results hopefully tomorrow

**Comment by chad-klumb** [comment]
results were the same as for current master, with the exception that `collpcm` was removed from CRAN at the time the revdeps were run (apparently it's now back up), so that particular package wasn't tested this time around

I say merge it

**Pull request merged**
